# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/panabaka100@gmail.com/New Pipeline 2026-01-03 19:15")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM dltravi.dlt_schema.sample_aggregation_jan_3_1915"))

# COMMAND ----------

from pyspark.sql.functions import upper

df=spark.read.table("dltravi.source.orders")
df=df.withColumn("order_status",upper(df.order_status))
display(df) 
